export const FIND_LIST_REQUEST ='FIND_LIST_REQUEST'
export const FIND_LIST_SUCCESS ='FIND_LIST_SUCCESS'
export const FIND_LIST_FAIL ='FIND_LIST_FAIL'

export const FIND_ACCEPT_REQUEST ='FIND_ACCEPT_REQUEST'
export const FIND_ACCEPT_SUCCESS ='FIND_ACCEPT_SUCCESS'
export const FIND_ACCEPT_FAIL ='FIND_ACCEPT_FAIL'
